In [29]:
#importing libraries
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.linear_model import Ridge,Lasso
from sklearn.metrics import mean_absolute_error,mean_squared_error
from sklearn.datasets import load_diabetes

In [2]:
diabetes = load_diabetes()
diabetes

{'data': array([[ 0.03807591,  0.05068012,  0.06169621, ..., -0.00259226,
          0.01990749, -0.01764613],
        [-0.00188202, -0.04464164, -0.05147406, ..., -0.03949338,
         -0.06833155, -0.09220405],
        [ 0.08529891,  0.05068012,  0.04445121, ..., -0.00259226,
          0.00286131, -0.02593034],
        ...,
        [ 0.04170844,  0.05068012, -0.01590626, ..., -0.01107952,
         -0.04688253,  0.01549073],
        [-0.04547248, -0.04464164,  0.03906215, ...,  0.02655962,
          0.04452873, -0.02593034],
        [-0.04547248, -0.04464164, -0.0730303 , ..., -0.03949338,
         -0.00422151,  0.00306441]], shape=(442, 10)),
 'target': array([151.,  75., 141., 206., 135.,  97., 138.,  63., 110., 310., 101.,
         69., 179., 185., 118., 171., 166., 144.,  97., 168.,  68.,  49.,
         68., 245., 184., 202., 137.,  85., 131., 283., 129.,  59., 341.,
         87.,  65., 102., 265., 276., 252.,  90., 100.,  55.,  61.,  92.,
        259.,  53., 190., 142.,  75., 142.

In [3]:
diabetes.data

array([[ 0.03807591,  0.05068012,  0.06169621, ..., -0.00259226,
         0.01990749, -0.01764613],
       [-0.00188202, -0.04464164, -0.05147406, ..., -0.03949338,
        -0.06833155, -0.09220405],
       [ 0.08529891,  0.05068012,  0.04445121, ..., -0.00259226,
         0.00286131, -0.02593034],
       ...,
       [ 0.04170844,  0.05068012, -0.01590626, ..., -0.01107952,
        -0.04688253,  0.01549073],
       [-0.04547248, -0.04464164,  0.03906215, ...,  0.02655962,
         0.04452873, -0.02593034],
       [-0.04547248, -0.04464164, -0.0730303 , ..., -0.03949338,
        -0.00422151,  0.00306441]], shape=(442, 10))

In [5]:
diabetes.target

array([151.,  75., 141., 206., 135.,  97., 138.,  63., 110., 310., 101.,
        69., 179., 185., 118., 171., 166., 144.,  97., 168.,  68.,  49.,
        68., 245., 184., 202., 137.,  85., 131., 283., 129.,  59., 341.,
        87.,  65., 102., 265., 276., 252.,  90., 100.,  55.,  61.,  92.,
       259.,  53., 190., 142.,  75., 142., 155., 225.,  59., 104., 182.,
       128.,  52.,  37., 170., 170.,  61., 144.,  52., 128.,  71., 163.,
       150.,  97., 160., 178.,  48., 270., 202., 111.,  85.,  42., 170.,
       200., 252., 113., 143.,  51.,  52., 210.,  65., 141.,  55., 134.,
        42., 111.,  98., 164.,  48.,  96.,  90., 162., 150., 279.,  92.,
        83., 128., 102., 302., 198.,  95.,  53., 134., 144., 232.,  81.,
       104.,  59., 246., 297., 258., 229., 275., 281., 179., 200., 200.,
       173., 180.,  84., 121., 161.,  99., 109., 115., 268., 274., 158.,
       107.,  83., 103., 272.,  85., 280., 336., 281., 118., 317., 235.,
        60., 174., 259., 178., 128.,  96., 126., 28

In [4]:
df = pd.DataFrame(data=diabetes.data,columns=diabetes.feature_names)

In [5]:
df

age       sex       bmi        bp        s1        s2        s3  \
0    0.038076  0.050680  0.061696  0.021872 -0.044223 -0.034821 -0.043401   
1   -0.001882 -0.044642 -0.051474 -0.026328 -0.008449 -0.019163  0.074412   
2    0.085299  0.050680  0.044451 -0.005670 -0.045599 -0.034194 -0.032356   
3   -0.089063 -0.044642 -0.011595 -0.036656  0.012191  0.024991 -0.036038   
4    0.005383 -0.044642 -0.036385  0.021872  0.003935  0.015596  0.008142   
..        ...       ...       ...       ...       ...       ...       ...   
437  0.041708  0.050680  0.019662  0.059744 -0.005697 -0.002566 -0.028674   
438 -0.005515  0.050680 -0.015906 -0.067642  0.049341  0.079165 -0.028674   
439  0.041708  0.050680 -0.015906  0.017293 -0.037344 -0.013840 -0.024993   
440 -0.045472 -0.044642  0.039062  0.001215  0.016318  0.015283 -0.028674   
441 -0.045472 -0.044642 -0.073030 -0.081413  0.083740  0.027809  0.173816   

           s4        s5        s6  
0   -0.002592  0.019907 -0.017646  
1   -0.039493 -0.068332 -0.092204  
2   -0.002592  0.002861 -0.025930  
3    0.034309  0.022688 -0.009362  
4   -0.002592 -0.031988 -0.046641  
..        ...       ...       ...  
437 -0.002592  0.031193  0.007207  
438  0.034309 -0.018114  0.044485  
439 -0.011080 -0.046883  0.015491  
440  0.026560  0.044529 -0.025930  
441 -0.039493 -0.004222  0.003064  

[442 rows x 10 columns]

In [6]:
df['target'] = diabetes.target

In [7]:
df

age       sex       bmi        bp        s1        s2        s3  \
0    0.038076  0.050680  0.061696  0.021872 -0.044223 -0.034821 -0.043401   
1   -0.001882 -0.044642 -0.051474 -0.026328 -0.008449 -0.019163  0.074412   
2    0.085299  0.050680  0.044451 -0.005670 -0.045599 -0.034194 -0.032356   
3   -0.089063 -0.044642 -0.011595 -0.036656  0.012191  0.024991 -0.036038   
4    0.005383 -0.044642 -0.036385  0.021872  0.003935  0.015596  0.008142   
..        ...       ...       ...       ...       ...       ...       ...   
437  0.041708  0.050680  0.019662  0.059744 -0.005697 -0.002566 -0.028674   
438 -0.005515  0.050680 -0.015906 -0.067642  0.049341  0.079165 -0.028674   
439  0.041708  0.050680 -0.015906  0.017293 -0.037344 -0.013840 -0.024993   
440 -0.045472 -0.044642  0.039062  0.001215  0.016318  0.015283 -0.028674   
441 -0.045472 -0.044642 -0.073030 -0.081413  0.083740  0.027809  0.173816   

           s4        s5        s6  target  
0   -0.002592  0.019907 -0.017646   151.0  
1   -0.039493 -0.068332 -0.092204    75.0  
2   -0.002592  0.002861 -0.025930   141.0  
3    0.034309  0.022688 -0.009362   206.0  
4   -0.002592 -0.031988 -0.046641   135.0  
..        ...       ...       ...     ...  
437 -0.002592  0.031193  0.007207   178.0  
438  0.034309 -0.018114  0.044485   104.0  
439 -0.011080 -0.046883  0.015491   132.0  
440  0.026560  0.044529 -0.025930   220.0  
441 -0.039493 -0.004222  0.003064    57.0  

[442 rows x 11 columns]

In [8]:
x = df.drop(columns=['target'])
x

age       sex       bmi        bp        s1        s2        s3  \
0    0.038076  0.050680  0.061696  0.021872 -0.044223 -0.034821 -0.043401   
1   -0.001882 -0.044642 -0.051474 -0.026328 -0.008449 -0.019163  0.074412   
2    0.085299  0.050680  0.044451 -0.005670 -0.045599 -0.034194 -0.032356   
3   -0.089063 -0.044642 -0.011595 -0.036656  0.012191  0.024991 -0.036038   
4    0.005383 -0.044642 -0.036385  0.021872  0.003935  0.015596  0.008142   
..        ...       ...       ...       ...       ...       ...       ...   
437  0.041708  0.050680  0.019662  0.059744 -0.005697 -0.002566 -0.028674   
438 -0.005515  0.050680 -0.015906 -0.067642  0.049341  0.079165 -0.028674   
439  0.041708  0.050680 -0.015906  0.017293 -0.037344 -0.013840 -0.024993   
440 -0.045472 -0.044642  0.039062  0.001215  0.016318  0.015283 -0.028674   
441 -0.045472 -0.044642 -0.073030 -0.081413  0.083740  0.027809  0.173816   

           s4        s5        s6  
0   -0.002592  0.019907 -0.017646  
1   -0.039493 -0.068332 -0.092204  
2   -0.002592  0.002861 -0.025930  
3    0.034309  0.022688 -0.009362  
4   -0.002592 -0.031988 -0.046641  
..        ...       ...       ...  
437 -0.002592  0.031193  0.007207  
438  0.034309 -0.018114  0.044485  
439 -0.011080 -0.046883  0.015491  
440  0.026560  0.044529 -0.025930  
441 -0.039493 -0.004222  0.003064  

[442 rows x 10 columns]

In [9]:
y = df['target']

In [10]:
y

0      151.0
1       75.0
2      141.0
3      206.0
4      135.0
       ...  
437    178.0
438    104.0
439    132.0
440    220.0
441     57.0
Name: target, Length: 442, dtype: float64

In [11]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2) 

In [12]:
x_train.shape,x_test.shape,y_train.shape,y_test.shape

((353, 10), (89, 10), (353,), (89,))

In [17]:
scaler = StandardScaler()
x_train_scaled = scaler.fit_transform(x_train)
x_test_scaled = scaler.transform(x_test)

In [18]:
x_train_scaled

array([[ 0.937652  , -0.96382662, -0.14985656, ..., -0.87669219,
         0.90757977, -0.81378312],
       [-1.0043285 ,  1.03753101,  2.86842551, ...,  1.51385557,
         1.50247856,  1.0458267 ],
       [-1.15968694,  1.03753101,  2.0514469 , ...,  2.31070482,
         1.78749004,  0.868721  ],
       ...,
       [-0.84897006, -0.96382662,  0.19055119, ..., -0.87669219,
        -0.33833307, -0.90233596],
       [-0.6159324 ,  1.03753101,  1.25716215, ..., -0.07984294,
         1.48531617,  2.90543651],
       [-1.54808304, -0.96382662,  0.80328515, ..., -0.07984294,
         1.43305763, -0.28246603]], shape=(353, 10))

In [19]:
x_test_scaled

array([[ 0.5492559 ,  1.03753101,  1.9606715 ,  2.05940312, -0.74176532,
        -0.70969476, -0.8979479 , -0.07984294,  0.77529433,  2.28556658],
       [ 1.17068966, -0.96382662, -1.23916136, -0.20846153,  1.11716177,
         1.04265856,  1.24404721, -0.48623606, -0.59904722,  0.95727385],
       [ 0.937652  ,  1.03753101, -0.76259051,  1.31996241, -0.09261618,
        -0.05340799, -0.18394953, -0.07984294,  0.3294577 ,  1.2229324 ],
       [-1.54808304, -0.96382662, -1.23916136, -1.78568856, -0.97781956,
        -0.64203633, -0.8979479 , -0.07984294,  0.02439128, -0.10536033],
       [-0.14985708, -0.96382662,  0.8713667 ,  1.02418613,  0.52702618,
        -0.53378284,  1.64071297, -0.87669219,  1.10600792,  0.60306246],
       [ 0.85997278,  1.03753101,  1.279856  , -0.89835971, -0.29916363,
         0.11573808, -0.5806153 , -0.07984294, -0.31634977,  0.24885106],
       [ 1.09301044, -0.96382662, -0.46757046, -1.63780042, -0.85979244,
        -0.83147993, -0.10461638, -0.87669219

In [20]:
x_train_scaled.shape,x_test_scaled.shape

((353, 10), (89, 10))

In [21]:
ridge_model = Ridge()
lasso_model = Lasso()

In [22]:
ridge_model.fit(x_train_scaled,y_train)

Ridge()

In [23]:
lasso_model.fit(x_train_scaled,y_train)

Lasso()

In [36]:
ridge_model_preiction = ridge_model.predict(x_test_scaled)

In [37]:
ridge_model_preiction

array([260.87682908,  86.99937684, 157.06121439, 116.0731071 ,
       211.98054821, 155.9962066 , 127.31748749, 160.8930654 ,
       144.89284557, 208.25422372,  96.60636144,  36.88720125,
       129.5323661 , 195.6128332 , 195.19897251,  92.75521865,
       146.55773615, 216.01001816, 115.7947906 , 170.41759982,
       232.08618133, 112.40553672, 146.79981067, 169.08500505,
       177.14243496,  78.28674556, 247.83726327, 157.1013373 ,
       164.14684572, 110.41992558, 228.37694422, 176.91173502,
       111.33581699, 118.6064486 , 231.77215026,  44.49033378,
        81.30838573, 127.83132601, 154.75261386,  53.93577332,
       178.72401495, 144.96625452, 122.57147564, 137.24308223,
        80.88907233, 153.44468148,  88.64696781, 130.51377256,
       167.44189711, 109.48139608, 236.84172058,  40.08490603,
       254.90550703, 111.98044976,  76.7557269 , 149.79900575,
       112.33804643,  95.96467699, 171.20238207, 192.55954222,
       243.99593488,  73.56748349, 247.53567532, 291.58

In [38]:
lasso_model_prediction = lasso_model.predict(x_test_scaled)

In [39]:
lasso_model_prediction

array([260.15185369,  91.37991196, 157.36066662, 114.67788627,
       208.73988481, 160.50584356, 126.71579582, 158.09833525,
       147.92380333, 201.96807356, 102.79023231,  43.79183815,
       138.79048798, 193.46153278, 189.3203947 ,  91.76131125,
       143.41964786, 216.27413711, 115.08256529, 169.00869319,
       225.37731228, 112.30902249, 144.46544891, 165.7842874 ,
       175.48828177,  80.98903466, 250.49610245, 159.91545819,
       166.95091932, 109.76749866, 233.43481733, 180.27270841,
       118.39125528, 118.98750286, 229.26176514,  44.03268151,
        82.95975341, 123.89172424, 166.62862031,  57.20967246,
       173.45161496, 148.39894765, 119.39574041, 136.36958463,
        84.55929267, 152.43471103,  88.35118999, 125.81514057,
       163.84372141, 106.06600819, 231.63879221,  50.57928373,
       256.9297667 , 109.40277855,  83.44589701, 150.57302158,
       104.67024459,  97.83338392, 170.79739457, 188.30135355,
       239.5148041 ,  72.20804218, 246.53024345, 288.65

In [40]:
ridge_error = mean_squared_error(y_test,ridge_model_preiction)
lasso_error = mean_squared_error(y_test,lasso_model_prediction)


In [41]:
ridge_error

2858.377082022735

In [42]:
lasso_error

2820.3272390658894

In [43]:
from sklearn.metrics import r2_score,root_mean_squared_error


In [44]:
r2_score(y_test,ridge_model_preiction)

0.504336152132023

In [47]:
r2_score(y_test,lasso_model_prediction)

0.5109342779319318

In [48]:
import pickle

In [50]:
with open('predict_diabetes.pkl','wb') as f:
    pickle.dump((ridge_model,lasso_model,scaler),f)